#!/bin/bash

wget http://www.oreilly.com/programming/free/files/modern-java-ee-design-patterns.mobi
wget http://www.oreilly.com/programming/free/files/object-oriented-vs-functional-programming.mobi
wget http://www.oreilly.com/programming/free/files/java-the-legend.mobi
wget http://www.oreilly.com/programming/free/files/introducing-java-8.mobi
wget http://www.oreilly.com/programming/free/files/a-whirlwind-tour-of-python.mobi
wget http://www.oreilly.com/programming/free/files/20-python-libraries-you-arent-using-but-should.mobi
wget http://www.oreilly.com/programming/free/files/hadoop-with-python.mobi
wget http://www.oreilly.com/programming/free/files/how-to-make-mistakes-in-python.mobi
wget http://www.oreilly.com/programming/free/files/functional-programming-python.mobi
wget http://www.oreilly.com/programming/free/files/python-in-education.mobi
wget http://www.oreilly.com/programming/free/files/from-future-import-python.mobi
wget http://www.oreilly.com/programming/free/files/trends-shaping-the-london-tech-scene.mobi
wget http://www.oreilly.com/programming/free/files/why-rust.mobi
wget http://www.oreilly.com/programming/free/files/c++-today.mobi
wget http://www.oreilly.com/programming/free/files/analyzing-visualizing-data-f-sharp.mobi
wget http://www.oreilly.com/programming/free/files/rxjava-for-android-app-development.mobi
wget http://www.oreilly.com/programming/free/files/swift-pocket-reference.mobi
wget http://www.oreilly.com/programming/free/files/ten-steps-to-linux-survival.mobi
wget http://www.oreilly.com/programming/free/files/open-by-design.mobi
wget http://www.oreilly.com/programming/free/files/getting-started-with-innersource.mobi
wget http://www.oreilly.com/programming/free/files/microservices-antipatterns-and-pitfalls.mobi
wget http://www.oreilly.com/programming/free/files/microservices-vs-service-oriented-architecture.mobi
wget http://www.oreilly.com/programming/free/files/software-architecture-patterns.mobi
wget http://www.oreilly.com/programming/free/files/migrating-cloud-native-application-architectures.mobi
wget http://www.oreilly.com/programming/free/files/reactive-microservices-architecture-orm.mobi
wget http://www.oreilly.com/programming/free/files/engineering-managers-guide-design-patterns.mobi
wget http://www.oreilly.com/programming/free/files/azure-for-developers.mobi
wget http://www.oreilly.com/iot/free/files/ambient-computing.mobi
wget http://www.oreilly.com/iot/free/files/governing-the-iot.mobi
wget http://www.oreilly.com/iot/free/files/iot-opportunities-challenges.mobi
wget http://www.oreilly.com/iot/free/files/creating-functional-teams-for-iot.mobi
wget http://www.oreilly.com/iot/free/files/when-hardware-meets-software.mobi
wget http://www.oreilly.com/iot/free/files/what-is-the-internet-of-things.mobi
wget http://www.oreilly.com/iot/free/files/software-above-device.mobi
wget http://www.oreilly.com/iot/free/files/hardware-by-the-numbers.mobi
